import type { Metadata } from "next";
import { Exo, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
  <html lang="en" className={cn("font-sans", geist.variable)}>
    <body className={`${exo.className} antialiased flex flex-col min-h-screen`}  suppressHydrationWarning >
      <ToastContainer position="top-right" autoClose={3000} />
      {/* Navbar */}
      <Navbar />

      {/* Content */}
      <main className="flex-1">
        {children}
      </main>

      {/* Footer */}
      <Footer />

    </body>
  </html>
);
}
