import type { Metadata } from "next";
import { Exo, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "./_components/Navbar/Navbar";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const exo = Exo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className={`${exo.className}  antialiased`}>


       {/* navbar  */}
         <Navbar />
     
        {children}
      </body>
    </html>
  );
}
